name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  testsuite:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.4']
        dependencies: ['highest']
        include:
          - php-version: '8.4'
            dependencies: 'lowest'

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl
          ini-values: zend.assertions = 1
          coverage: pcov

      - name: Composer install
        uses: ramsey/composer-install@v3
        with:
          dependency-versions: ${{ matrix.dependencies }}

      - name: Run PHPUnit
        run: |
          if [[ ${{ matrix.dependencies }} == 'highest' ]]; then
            export XDEBUG_MODE=coverage;
            vendor/bin/phpunit --display-skipped --display-deprecations --display-warnings --coverage-clover=coverage.xml
          else
            vendor/bin/phpunit --display-deprecations --display-warnings
          fi

      - name: Submit code coverage
        if: success() && matrix.dependencies == 'highest'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}